// sim_ecore
// Copyright (c) 2021-2022, Joshua Scoggins
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
// ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
            X(0x08, b)
            X(0x09, call)
            X(0x0A, ret)
            X(0x0B, bal)
            X(0x10, bno)
            X(0x11, bg)
            X(0x12, be)
            X(0x13, bge)
            X(0x14, bl)
            X(0x15, bne)
            X(0x16, ble)
            X(0x17, bo)
            X(0x18, faultno)
            X(0x19, faultg)
            X(0x1A, faulte)
            X(0x1B, faultge)
            X(0x1C, faultl)
            X(0x1D, faultne)
            X(0x1E, faultle)
            X(0x1F, faulto)
            X(0x20, testno)
            X(0x21, testg)
            X(0x22, teste)
            X(0x23, testge)
            X(0x24, testl)
            X(0x25, testne)
            X(0x26, testle)
            X(0x27, testo)
            X(0x30, bbc)
            X(0x31, cmpobg)
            X(0x32, cmpobe)
            X(0x33, cmpobge)
            X(0x34, cmpobl)
            X(0x35, cmpobne)
            X(0x36, cmpoble)
            X(0x37, bbs)
            X(0x38, cmpibno)
            X(0x39, cmpibg)
            X(0x3A, cmpibe)
            X(0x3B, cmpibge)
            X(0x3C, cmpibl)
            X(0x3D, cmpibne)
            X(0x3E, cmpible)
            X(0x3F, cmpibo)
            X(0x80, ldob)
            X(0x82, stob)
            X(0x84, bx)
            X(0x85, balx)
            X(0x86, callx)
            X(0x88, ldos)
            X(0x8A, stos)
            X(0x8C, lda)
            X(0x90, ld)
            X(0x92, st )
            X(0x98, ldl)
            X(0x9A, stl)
            X(0xA0, ldt)
            X(0xA2, stt)
            X(0xB0, ldq)
            X(0xB2, stq)
            X(0xC0, ldib)
            X(0xC2, stib)
            X(0xC8, ldis)
            X(0xCA, stis)

            X(0x580, notbit)
            X(0x581, logicalAnd)
            X(0x582, andnot)
            X(0x583, setbit)
            X(0x584, notand )
            X(0x586, logicalXor )
            X(0x587, logicalOr )
            X(0x588, logicalNor )
            X(0x589, logicalXnor )
            X(0x58A, logicalNot )
            X(0x58B, ornot )
            X(0x58C, clrbit )
            X(0x58D, notor )
            X(0x58E, logicalNand )
            X(0x58F, alterbit )
            X(0x590, addo)
            X(0x591, addi)
            X(0x592, subo)
            X(0x593, subi )
#ifdef CORE_ARCHITECTURE_EXTENSIONS
            X(0x594, cmpob)
            X(0x595, cmpib)
            X(0x596, cmpos)
            X(0x597, cmpis)
#endif
            X(0x598, shro)
            X(0x59A, shrdi)
            X(0x59B, shri)
            X(0x59C, shlo)
            X(0x59D, rotate)
            X(0x59E, shli)
            X(0x5A0, cmpo)
            X(0x5A1, cmpi)
            X(0x5A2, concmpo)
            X(0x5A3, concmpi)
            X(0x5A4, cmpinco)
            X(0x5A5, cmpinci)
            X(0x5A6, cmpdeco)
            X(0x5A7, cmpdeci)
            X(0x5AC, scanbyte)
            X(0x5AD, bswap)
            X(0x5AE, chkbit)
            X(0x5B0, addc)
            X(0x5B2, subc)
#ifdef CORE_ARCHITECTURE_EXTENSIONS
            X(0x5B4, intdis)
            X(0x5B5, inten)
#endif
            X(0x5CC, mov)
#ifdef CORE_ARCHITECTURE_EXTENSIONS
// not found on Kx and Sx processors
            X(0x5D8, eshro)
#endif
            X(0x5DC, movl)
            X(0x5EC, movt)
            X(0x5FC, movq)
            // i960Sx specific {
            X(0x600, synmov)
            X(0x601, synmovl)
            X(0x602, synmovq)
            X(0x615, synld)
            // }
            X(0x610, atmod)
            X(0x612, atadd)
            X(0x640, spanbit)
            X(0x641, scanbit)
#ifdef NUMERICS_ARCHITECTURE
            X(0x642, daddc)
            X(0x643, dsubc)
            X(0x644, dmovt)
#endif
            X(0x645, modac)
            X(0x650, modify)
            X(0x651, extract)
            X(0x654, modtc)
            X(0x655, modpc)
#ifdef CORE_ARCHITECTURE_EXTENSIONS_JX_SPECIFIC
            X(0x658, intctl)
            X(0x659, sysctl)
            X(0x65B, icctl)
            X(0x65C, dcctl)
            X(0x65D, halt)
#endif
            X(0x660, calls)
            X(0x66B, mark)
            X(0x66C, fmark)
            X(0x66D, flushreg)
            X(0x66F, syncf)
            X(0x670, emul)
            X(0x671, ediv)
            X(0x701, mulo)
            X(0x708, remo)
            X(0x70B, divo)
            X(0x741, muli)
            X(0x748, remi)
            X(0x749, modi)
            X(0x74B, divi)
#ifdef CORE_ARCHITECTURE_EXTENSIONS
            X(0x780, addono )
            X(0x781, addino )
            X(0x782, subono )
            X(0x783, subino )
            X(0x784, selno )
            X(0x790, addog )
            X(0x791, addig )
            X(0x792, subog )
            X(0x793, subig )
            X(0x794, selg )
            X(0x7A0, addoe )
            X(0x7A1, addie )
            X(0x7A2, suboe )
            X(0x7A3, subie )
            X(0x7A4, sele )
            X(0x7B0, addoge )
            X(0x7B1, addige )
            X(0x7B2, suboge )
            X(0x7B3, subige )
            X(0x7B4, selge )
            X(0x7C0, addol )
            X(0x7C1, addil )
            X(0x7C2, subol )
            X(0x7C3, subil )
            X(0x7C4, sell )
            X(0x7D0, addone)
            X(0x7D1, addine)
            X(0x7D2, subone)
            X(0x7D3, subine)
            X(0x7D4, selne)
            X(0x7E0, addole)
            X(0x7E1, addile)
            X(0x7E2, subole)
            X(0x7E3, subile)
            X(0x7E4, selle)
            X(0x7F0, addoo)
            X(0x7F1, addio)
            X(0x7F2, suboo)
            X(0x7F3, subio)
            X(0x7F4, selo)
#endif
